language: ruby
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
  include:
    - rvm: 1.9.3
    - rvm: 2.1
    - rvm: 2.2.6
    - rvm: 2.3.1
    - rvm: 2.4.0
    - rvm: jruby-9.1.15.0
      env:
        - JRUBY_OPTS="--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Xss2m -Xcompile.invokedynamic=false -J-Xmx1536m"
    - rvm: ruby-head
